// Post-build step: stamp the service worker template into its real workers.
//
// Vite content-hashes every asset filename, so the shell an app needs offline is
// only knowable AFTER the build. This scans web/dist and writes, from the single
// template at public/sw.js:
//
//   dist/sw.js       → the real member app  (scope "/",     shell /member)
//   dist/sw-demo.js  → the standalone demo  (scope "/demo", shell /demo)
//
// Each gets its own cache prefix and a version derived from the contents of the
// files it precaches, so shipping new assets busts that worker's old cache
// instead of serving a stale mix — and so the two never collide.
//
// Run automatically by `npm run build` (see web/package.json).

import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

const DIST = resolve(process.cwd(), 'dist');
const TEMPLATE = join(DIST, 'sw.js');

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    out.push(...(statSync(p).isDirectory() ? walk(p) : [p]));
  }
  return out;
}

const all = walk(DIST).map((p) => '/' + relative(DIST, p).split(/[\\/]/).join('/'));

// Every hashed JS/CSS chunk. We take the WHOLE assets/ dir rather than parsing
// the HTML: entries reach their main chunk through a *dynamic* import, so that
// chunk appears in no <script> tag and an HTML scan would miss it and break
// offline. dist is well under a megabyte — over-including is free insurance.
const chunks = all.filter((u) => u.startsWith('/assets/'));

// Per-app static assets on top of the chunks.
const memberAssets = all.filter(
  (u) =>
    u === '/inter.woff2' ||
    u === '/apple-touch-icon.png' ||
    u === '/icon-192.png' ||
    u === '/icon-512.png' ||
    u.startsWith('/review/'),
);
const insightsAssets = all.filter((u) => u === '/inter.woff2' || u.startsWith('/vox/'));

const template = readFileSync(TEMPLATE, 'utf8');
const MARKER = /\/\* __SW_BUILD__ \*\/[\s\S]*?\/\* __SW_BUILD_END__ \*\//;
if (!MARKER.test(template)) {
  console.error('build-sw: marker block not found in dist/sw.js — did the template change?');
  process.exit(1);
}

function emit({ outFile, cachePrefix, shellUrl, shellFile, manifest, assets }) {
  // The clean URL is what the manifest's start_url and the home-screen icon open.
  const precache = [shellUrl, shellFile, manifest, ...chunks, ...assets];

  const h = createHash('sha256');
  h.update(cachePrefix);
  for (const u of precache) {
    try {
      h.update(readFileSync(join(DIST, u.slice(1))));
    } catch {
      /* clean-URL alias with no file of its own — skip */
    }
  }
  const version = h.digest('hex').slice(0, 12);

  const block = `/* __SW_BUILD__ */
// GENERATED by scripts/build-sw.mjs — do not edit by hand.
const VERSION = ${JSON.stringify(version)};
const CACHE_PREFIX = ${JSON.stringify(cachePrefix)};
const SHELL_URL = ${JSON.stringify(shellUrl)};
const SHELL_FILE = ${JSON.stringify(shellFile)};
const PRECACHE = ${JSON.stringify(precache, null, 2)};
/* __SW_BUILD_END__ */`;

  writeFileSync(join(DIST, outFile), template.replace(MARKER, block));
  console.log(`build-sw: ${outFile} — ${precache.length} files, cache ${cachePrefix}-${version}`);
}

emit({
  outFile: 'sw.js',
  cachePrefix: 'loopedin-member',
  shellUrl: '/member',
  shellFile: '/member.html',
  manifest: '/manifest.webmanifest',
  assets: memberAssets,
});

emit({
  outFile: 'sw-demo.js',
  cachePrefix: 'loopedin-demo',
  shellUrl: '/demo',
  shellFile: '/demo.html',
  manifest: '/demo.webmanifest',
  assets: memberAssets,
});

emit({
  outFile: 'sw-insights.js',
  cachePrefix: 'loopedin-insights',
  shellUrl: '/insights',
  shellFile: '/insights.html',
  manifest: '/insights.webmanifest',
  assets: insightsAssets,
});
