// Post-build step: stamp the service worker with the real precache list.
//
// Vite content-hashes every asset filename, so the shell the member app needs
// offline is only knowable AFTER the build. This scans web/dist and rewrites
// the generated block in dist/sw.js with (a) the exact URLs to precache and
// (b) a version derived from their contents, so shipping new assets busts the
// old cache instead of serving a stale mix.
//
// Run automatically by `npm run build` (see web/package.json).

import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

const DIST = resolve(process.cwd(), 'dist');
const SW = join(DIST, 'sw.js');

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    out.push(...(statSync(p).isDirectory() ? walk(p) : [p]));
  }
  return out;
}

const all = walk(DIST).map((p) => '/' + relative(DIST, p).split(/[\\/]/).join('/'));

// What the MEMBER app needs to boot and run with no network.
//   • every hashed JS/CSS chunk — the member entry dynamically imports its app
//     chunk, so that file is NOT referenced in member.html and a naive
//     "parse the HTML" approach would miss it and break offline. The whole
//     assets/ dir is well under a megabyte, so take all of it.
//   • the shell HTML, the brand font, the PWA icons, and the review media.
const precache = all.filter(
  (u) =>
    u.startsWith('/assets/') ||
    u === '/member.html' ||
    u === '/inter.woff2' ||
    u === '/manifest.webmanifest' ||
    u === '/apple-touch-icon.png' ||
    u === '/icon-192.png' ||
    u === '/icon-512.png' ||
    u.startsWith('/review/'),
);

// The clean URL is what the manifest's start_url and the home-screen icon open.
precache.unshift('/member');

// Version = hash of the precached files' contents, so any asset change rolls
// the cache name and the old cache is purged on activate.
const h = createHash('sha256');
for (const u of precache) {
  if (u === '/member') continue; // an alias of member.html, already hashed below
  try {
    h.update(readFileSync(join(DIST, u.slice(1))));
  } catch {
    /* not on disk (alias) — skip */
  }
}
const version = h.digest('hex').slice(0, 12);

const block = `/* __SW_BUILD__ */
// GENERATED by scripts/build-sw.mjs — do not edit by hand.
const VERSION = ${JSON.stringify(version)};
const PRECACHE = ${JSON.stringify(precache, null, 2)};
/* __SW_BUILD_END__ */`;

const src = readFileSync(SW, 'utf8');
const re = /\/\* __SW_BUILD__ \*\/[\s\S]*?\/\* __SW_BUILD_END__ \*\//;
if (!re.test(src)) {
  console.error('build-sw: marker block not found in dist/sw.js — did the template change?');
  process.exit(1);
}
writeFileSync(SW, src.replace(re, block));

console.log(`build-sw: ${precache.length} files precached, version ${version}`);
